image: node:lts-alpine

stages:
  - validate
  - build
  - test
  - docs

cache:
  paths:
    - node_modules/

before_script:
  - npm install

tsc:
  stage: validate
  script:
    - npm run check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - when: never

lint:
  stage: validate
  script:
    - npm run lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - when: never

build:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - when: never

test:
  stage: test
  script:
    - npm run coverage
  coverage: '/Lines\s*:\s*([\d.]+)%/'
  artifacts:
    when: always
    reports:
      junit:
        - coverage/junit-report.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - when: never

pages:
  stage: docs
  script:
    - apk add --no-cache python3 py3-pip py3-virtualenv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --no-cache-dir mkdocs mkdocs-material
    - npm run docs
    - mkdocs build
  artifacts:
    paths:
      - public 
  rules:
    # Only run on version tags like "v1", "v1.0", "v1.0.0", or "v1.0.0-revision"
    - if: '$CI_COMMIT_TAG =~ /^v([0-9]+)(\.[0-9]+)+(\-[a-z0-9]+)?$/'
    - when: never